modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="dontclearmytag"
version="${file.jarVersion}"
displayName="Don't Clear My Tag"
authors="Florens"
description="Logs a warning when a datapack overrides a tag"

[[dependencies.dontclearmytag]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dontclearmytag]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
